__title__ = "pylint-elasticsearch-dsl"
__description__ = "pylint plugin for the elasticsearch-dsl package"
__url__ = "https://github.com/glostis/pylint-elasticsearch-dsl"
__author__ = """Guillaume Lostis"""
__author_email__ = "g.lostis@kayrros.com"
__version__ = "0.1.1"
